apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-k8s-app
  labels:
    app: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
    spec:
      containers:
        - name: my-k8s-app
          image: gautamjha3112002/my-k8s-app:0.1
          ports:
            - containerPort: 8080
